"""Protocol constants shared with firmware."""

MAGIC = 0xAB

PKT_TALLY_STATUS = 0x01
PKT_IDENTIFY = 0x02
PKT_MAC_BROADCAST = 0x03
PKT_PAIR_NAME = 0x04

TALLY_OFF = 0
TALLY_PGM = 1
TALLY_PVW = 2

MAX_CHANNELS = 32
MAX_LABEL_BYTES = 24

TALLY_STATUS_PACKET_LEN = 12
IDENTIFY_PACKET_LEN = 8
MAC_BROADCAST_PACKET_LEN = 8

IDENTIFY_CMD_START = 0x01
IDENTIFY_CMD_STOP = 0x00
